/*markdown
## Aufgabenblatt 1
### Einfache SQL-Anfragen
*/

/*markdown
#### Aufgabe 1
Verbinden Sie sich mit dem Datenbank Server. Die Credentials dafür sind:
- host: 
- Port: 5432
- database mondial
- user: student
- password: Inf20ormatik
- driver: postgres
*/

/*markdown
##### Aufgabe 2: Zeilen in der `country`
Wie viele Zeilen hat die Relation `country`?
*/



/*markdown
#### Aufgabe 3: Länder in `country`
Geben Sie die Zahl der Länder an, die in der Realtion `country` eingetragen sind.
*/

/*markdown
#### Aufgabe 4: Länder mit mehr als 100 Millionen Einwohnern
Gib alle Länder aus, die mehr als 100 Millionen Einwohner haben. Zeige den Ländernamen und die Einwohnerzahl an.
*/

/*markdown
#### Aufgabe 5: Alle Länder in Europa
Gib die Namen aller Länder in Europa aus.
*/

/*markdown
#### Aufgabe 6: Die zehn bevölkerungsreichsten Länder
Gib die zehn Länder mit der höchsten Bevölkerung aus.
*/

/*markdown
#### Aufgabe 7: Alle Städte in Deutschland
Gib alle Städte in Deutschland und in einer weiteren Anfrage die Anzahl der Städte aus.
*/

/*markdown
#### Aufgabe 8: Mitgliedsstaaten der UNO
Gib alle Länder aus, die Mitglied der UNO sind.
*/

/*markdown
#### Aufgabe 9: Länder mit A
 Schreibe eine SQL-Abfrage, die alle Länder abruft, deren Name mit dem Buchstaben 'A' beginnt.
*/

/*markdown
#### Aufgabe 10: Länder Südamerikas
Schreibe eine SQL-Abfrage, die die Namen aller Länder abruft, die in Südamerika liegen, und sortiere sie nach ihrer Fläche in aufsteigender Reihenfolge.
*/

/*markdown
#### Aufgabe 11: 
Schreibe eine SQL-Abfrage, die den Namen und die Regierungsform aller Länder abruft, die eine Republik sind.
*/